#+TITLE: Perils of ADvice 

- /The Stanford Business School 5-Step Entrepreneurial Program/ The
  most recent business best seller/ 5-step program is commiditized
  knowledge. It's incredulious to believe that a course /anyone has
  access to/, a YouTube video /anyone could watch/ could proffer any
  knowledge of real value. 
  - /Advice and Lotto Tickets-  Another factor that makes
     advice hard to translate is luck and randomness. Most communicated
     advice is flawed: Even if the giver of the advice is innocuous,
     advice is like handing you the numbers to their winning lottery
     ticket. We don't see the people who failed with this advice.
  - /Rare Knowledge is Valuable/ 
  - /Business is predicated on Discovery/ What a million people know
    isn't worth knowing. Any real vaule of a business is based on
    discovering a "secret," - that is, somehting not many people know
    or believe to be true. Real value is made through Differentitade,
    rare, inimitable qualities of businesses. One-in-a-kind products. 
  - /Business Plans/ Business PLans are faulty thinking. THis was the
    case for Coca Cola, Tiffany, Kodak, and Aspirin. 
  - 
  - /Trial and Error/Empricism/Practice Over Theories/ You can learn
    creative experimentation can lead to outcomes you can't
    predict. Feel free to take all matter of risk in this domain. 
