#+TITLE: Virtue, Ethics,  Stories, 

#+BEGINQUOTE
This, I submit, is the freedom of a real education, of learning how to
be well-adjusted. You get to consciously decide what has meaning and
what doesn’t. You get to decide what to worship. Because here’s
something else that’s weird but true: in the day-to-day trenches of
adult life, there is actually no such thing as atheism. There is no
such thing as not worshipping. Everybody worships. The only choice we
get is what to worship. And the compelling reason for maybe choosing
some sort of god or spiritual-type thing to worship–be it JC or Allah,
be it YHWH or the Wiccan Mother Goddess, or the Four Noble Truths, or
some inviolable set of ethical principles–is that pretty much anything
else you worship will eat you alive. If you worship money and things,
if they are where you tap real meaning in life, then you will never
have enough, never feel you have enough. It’s the truth. Worship your
body and beauty and sexual allure and you will always feel ugly. And
when time and age start showing, you will die a million deaths before
they finally grieve you. On one level, we all know this stuff
already. It’s been codified as myths, proverbs, clichés, epigrams,
parables; the skeleton of every great story. The whole trick is
keeping the truth up front in daily consciousness.”

#+ENDQUOTE

-- David Foster Wallace, Kenyon College Commencement Speech 


LIfe is not a story, and don't try to mae it one. 
Don't look for meaning in your suffering. 

Life has no meaning, it does not matter what you do with it. 

For Homer, human life is a succession of contigencies. all good things
are vulnerable to fortune. 

Aesthetics, erudation, , risk taking 

Explore protocols for dealing with a random world.

The stoics advocated focusing on behavior, rather than result.

 The Pyrrhonian
skeptics advocated the need to remain skeptical about the consequence
of any action, as we are not able to gauge whether it should have
beneficial or adverse effects.

ACts of courage - standing up against fraudsters. starting
businesses. 

In virtue ethics, the only excellence worth attaining is being human. 
