#+TITLE: Silenced by Modernity 



/On Cicero arriving at the tomb of Archimedes/
In Cicero's /On Old Age/, he recounts seeing the tomb of archimedes,
the godfather of Mathematics, shrouded in overgrowth. 

As the old saying goes, Those who fail to learn what our ancestors
know are doomed to repeat it. 

More importantly, let us focus on what they /did/, not what they
thought they knew or what historians thought they thought they knew. 

Mother Nature leaves hints, traces. Instincts. The obvious answers are
hidden in plain sight. 

In practice, Our ancestors focused on survival. Our ancestors listened
to Mother nature. We are foolish not to heed these lessons. 


-- 


Modernity shuts out qualities of Nature that are fatally ignored. 
- commoditization over realtionships - 
- life is more random than we think. 
- sterilizes the randomness of real life with simplified models -
  gyms, schools, prediction models, etc. Modernity seeks to deprive us of life's innate sense of variability
and randomness. When forced to overcompensate we become better off
when not under such conditions.
- Talk is a lot cheaper. /Looking good is more important than doing good/
- product for process - what makes you a hero is how you fight, not if
  you win. 


By the Lindy Effect, you should know 20 times more about history of
the past 2000 years than that of the past 100 years.

In fact, not only most people know more about the past 100 years, but
they knew even more about the past 100 days.

Further, history is not geopolitics (who met whom) or wars, but an
understanding of what people used, ate, produced, thought, and argued
about.

What I am now trying to do, in a systematic way, is the opposite
operation, that is, to reexpress the present entirely in terms that an
ancient person would have grasped, that is, to propagate the mentality
forward, while incorporating modern gains in ethics such as
"equality", social justice, etc. 

---
So using Lindy as a bullshit detection mechanism, I can eliminate
modern notions such as "success", "achievement", etc., those that do
not have a moral dimension

