#+TITLE:  Killing Hope & Amor Fati 


1. /Personal Dignity/ 

Failure is felt by everyone, - no matter how great you are. 
At their lowest, in epic heroes face deep existential dread 
The mighty Achilles, or  Dante on his personal odyssey through
Hades, - they wish they were never born. 

They don't give up 
Because there is no such thing as failure. Only Death. 


There will always be more who lose than those who win. 
Risk Takers in any discipline can't fake 

Let us heed the words of poet emily Dickinson: 

#+BEGIN_QUOTE
Success is counted sweetest
By those who ne'er succeed.
To comprehend a nectar
Requires sorest need.

Not one of all the purple Host
Who took the Flag today
Can tell the definition
So clear of victory

As he defeated – dying –
On whose forbidden ear
The distant strains of triumph
Burst agonized and clear!
#+END_QUOTE
-- Emily Dickinson 

 Traditionally while the war was being fought the flag of each side
 were held up on the field. And holding the flag made you-- before
 anyone else-- the enemy's target. Don't let the flag fall. 

At the end of the day, we don't have much say over fate. But we decide
how we hold ourselves.  Should    fate turn against you, do not play
victim. Do not complain. Be worthy. 
don't change the rules just because they odds are against you.

For a soldier, for an entrepreneur, there is no failure, only
death. which is happening anyway. 

  
Life is about execution rather than purpose. Don't worry about who you
 are. You will be remembered for what you do. Always. 
It's not what you say, it's how you say it. 
Calling good to everything.  Life belongs to those who
 embrace it no matter what their plight. Life is bigger than you or
 me. Life is happening to you right now. Hope is like banging on the
 locked door trying to get out, opening it only to find that /the door
 opens outward/

Eternal Reccurance - 

3. 
