
#+TITLE: Finding Time 


Do things that serve a purpose and that you enjoy doing for it's own
sake. 

Life is meant to be savoured, not rushed thorugh. 

Don't something that you need to speedread, don't watch a video that
you have to watch at 2x, 

If you're not fully engaged or easily distracted, (if you have to
listen to music while doing something), switch to a better way or do
something else. 

How Productive you are might just mean how good you are at forcing
yourself to do something you don't like doing.

The optimal path is never the shortest one. 

Everyone is trying to be the
  best, or top 1% percent. Few are trying to do what they like
  regardless of what everyone else does.  Competition is for chasing
  the preferences of others; playing someone else’s game.  Their rules, their
  way, their game. There are no rules, no boundaries. Play your game;
  not theirs. You have a real life if and only if you do not compete
  with anyone in any of your pursuits. 


- cultivate a long attention span 


Don't run for trains. 


