#+TITLE: Pursuits of Your Own  

 /The Promise of Marshmallows/ In popular psychology there's 'the
      Marshmallow Test' or something, which participants choose
      between a single marshmallow at the the start or can opt to wait
      15 minutes to receive an additional one. The truth about life is
      that we aren't guaranteed the second marshmallow. Carefully
      consider what is worth delaying gratification for. With things
      like feeling happiness, having a romantic partner, getting a
      Nobel or A Booker where luck plays a large role (hidden or
      forgotten). 


 /Abandoning Hope/ Try to kill anything called hope in you. You never
  want to put yourself in a sutiation where you wish very badly for
  something specific to happen to you, an event where tomorrow would
  suddenly make a big difference for the rest of your life. 
  - say, the outcome of a job interview, a lawsuit, winning the lotto,
    meeting a significant other, getting a paper accepted, have gold
     rise, your boss dies, or other events that can markedly change your life. If this is the case for
    you are royally enslaved to circumstances. 
  - Take good events when they happen, but don't depend on them like a
    loser. 
  - Organize yourself in a way to not have to dream for a better
    tomorrow or day after.
  - Life is happening to you right now. Hope is like banging on the
    locked door trying to get out, opening it only to find that /the door
    opens outward/

It's foolish to complain you
       don't have enough time. We shouldn't know when the week begins
       or ends. Not being prisoner to a schedule ro calendar, an alarm clock or
       wristwatch. Rehearsed conversations, rehearsed laughs.  if
       luxury is not creating more and more varied options for life,
       you're doing it wrong. 

It's hard to lose playing your own game. 


Everyone is trying to be the
  best, or top 1% percent. Few are trying to do what they like
  regardless of what everyone else does.  Competition is for chasing
  the preferences of others; playing someone else’s game.  Their rules, their
  way, their game. There are no rules, no boundaries. Play your game;
  not theirs. You have a real life if and only if you do not compete
  with anyone in any of your pursuits. 


As with the Sour Grapes from
Aesop’s fable, fate can hold the grapes out of reach, but we get to
decide whether or not they are sour. Rejecting the grapes outright is
in itself its own more rewarding. It is hard to lose at your own
game. 


Stop doing somethign when it becoems effortful. 
