
#+TITLE: Productivity Versus Savoring 

Having fun is a performance enhancing drug. 

Do things that serve a purpose and that you enjoy doing for it's own
sake. 

Life is meant to be savoured, not rushed thorugh. 

Don't something that you need to speedread, don't watch a video that
you have to watch at 2x, 

If you're not fully engaged or easily distracted, (if you have to
listen to music while doing something), switch to a better way or do
something else. 

How Productive you are might just mean how good you are at forcing
yourself to do something you don't like doing.

The optimal path is never the shortest one. 

 
2. /Abandoning Hope/ Try to kill anything called hope in you. You never
  want to put yourself in a sutiation where you wish very badly for
  something specific to happen to you, an event where tomorrow would
  suddenly make a big difference for the rest of your life. 
  - say, the outcome of a job interview, a lawsuit, winning the lotto,
    meeting a significant other, getting a paper accepted, have gold
     rise, your boss dies, or other events that can markedly change
    your life. If this is the case for    you are royally enslaved to
    circumstances. 
  - Take good events when they happen, but don't depend on them like a
    loser. 
  - Organize yourself in a way to not have to dream for a better
    tomorrow or day after.

- cultivate a long attention span 


Don't run for trains. 



It's foolish to complain you don't have enough time. 

We shouldn't know when the week begins or ends. Not being prisoner to
a schedule ro calendar, an alarm clock or wristwatch. 

Don't run for trains. 

Speed 
- Slowly as possible, to savor it, 
- Why read something that you’d want to Speeding reading, watching at 2x speed 
	- fast drivers just get to the next red light quickly 
Never do work you can’t get lost in 
