#+TITLE: Reinstating Dimensionality 
 
* Wake up the body and mind 
With too much noise, performance of systems suffer. But surprisingly,
/too little/ noise could be just as bad. Some noise is good and
necessary for health. Any complex system, the mind, the body,
information systems, etc. 


* Modernity drains Life's Variability and Randomness. 
Modernity seeks to deprive us of life's innate sense of variability
and randomness. When forced to overcompensate we become better off
when not under such conditions. 


* Dimensionality 

* The essence of Life is light volatility.
  1) Human bones are strengthened through episodic stress. Falling
    asleep is easier with background noise. 
  2) Interpersonal relationships are well maintained when problems (and
    conversations) are had early. 
  3) Innovation and Discovery. Innovation happen through aggressive
    trial and by accident, discovering a product or use of a product
    never seen before. Increase your exposures and fail
    early and cleanly. Creativity is your number of trials.
  4) The uberwealth of cities on the East Coast as a motivator
     compensates for the bad weather, lack of scenic Nature, and
     miserable train rides.


No food can compare to the food we get after an episode of hunger; and
no liquid will ever improve on the taste of water after a prolonged
period of thirst. The best days can be recovering a lost wallet or
phone. The greatest acts of kindness you expericnec may be from total
strangers. 

* Risk 
When we have something to lose, or risk failure, we become desparately
to find out as much as we can about a subject. Much like the pilot of
a plane is maximally paranoid or an  addict's cunning comes from to
procure drugs. Learn out of necessity. 

* Dimensionality 

* Cultivating a long attenion span 
Modernity by definition removes the variability out of life. 

Curriculums suffers from one-size-fits-all effect. The mind's
attention 

Notice when you a book starts to bore you. As soon as that's the case,
switch to another book. 

If schools wanted to resemble
real life, they would only care about the subject in which the stduent
has the  highest grade and ignore the others, In a convex world, the
average is of zero significance. 

     - /Avoiding Boredom/ If you get bored easily that means your
       /b***t/ detector is functioning properly. Evaluate curiosity
       daily, Read accordingly. Notice when you a book starts to bore
       you. As soon as that's the case, switch to another book. (This
       is where it is extremely helpful but not necessary to own a lot
       of books ) Don't read something that you need to speedread,
       don't watch a video that you have to watch at 2x, If you're not
       fully engaged or easily distracted, find a better way or don't
       do it. 
   
  2) /Leisure is Fertile without Distraction/ The mind is most
     intelligent while devoted to effortless activity. When freed
     from constraints, work, schedules, the mind discoveries
     opportunities that it didn't see before. As anyone who might have
     taken a shower before would realize. Go for a walk without a
     phone, without listening to music. [fn:4] 


*  /Diet and Exercise/ Diets & Exercise Regimens tax the body with
  chronic stressors. Gyms are sterilized environments that work one
  muscle at a time, making the part stronger at teh expense of the
  whole. Diets through modern constructions rely on strong willed
  moderation instead of randomized fasting and volume intake. To
  simulate natural exercise and dietary conditions, try Hiking on
  rocky trails with steep inclines. Deadlift your maxlift on a
  barbell. Never eat foods out of a box, and avoid modernized diet
  foods. Randomly skip meals, and work out when hungry. 
