#+TITLE: Philosophical Notebook 
#+SUBTITLE: or, What Our Ancestors Forgot to Tell Us
#+AUTHOR: Joseph Ruocco 
#+OPTIONS: toc:nil


# #  * Introduction 
# ** Old wisdom stays young
# The importance of Ancient ideas are because they are so old. Old ideas
# have stood the test of time. 
# 
#  There is an allure that ancient philosophy speaks to the right
#  soul. The art of Living well the real "moral" philopshers taught was
#  to approcah life with humility and love of our Nature, its beauty,
#  knowledge, and uncertainty. 
#  The Stoics, the skeptics, the epicureans, other ancient schools of
# thought. They were all right. We humans, curious by nature, need to
# explore, adventure, rationally stepping forward by keeping what suits
# us and discarding the rest. Ethics are different at scale. IN random
# domains. With risk taking I'm a stoic, with knowledge I'm a
# skepticist/empiricst, with aesthetics I'm an epicurean.    
# If we seek to fill the shoes of our ancestors,to have the same impact
# as our ancestors.  We have to devote ourselves to risk taking. We have
# to prudently prepare for a world we don't quite know what to expect
# from. We have to take up what our ancestors left behind.  Of course,
# like Seneca, we can keep the fruits and enjoy life.  
# 
# ** Several Proclamations around a central Stoic Idea. . 
# Few figures stress the importnace of robustness than the Stoics. And
# the heavy criticality of this idea its not surprising that fellows
# separated by continents or centuries have the same idea: 1) *Nihil
# Periditi, C. 4BC, Roman Empire* - It is recorded in response to having
# suffered a terrible misfortune, Seneca,(or Zeno of Citium?) the roman
# statesman is to have reported "Nihil Perditi" - I have lost
# nothing. For the Stoics, nothing could have been taken away from them
# that they considered a good. Nearly all the letters of Seneca echo
# against loss aversion. 2) *Amor Fati 1888 Germany* Nietzche learned
# from Seneca the Amor   Fati - the love of fate. He proclaims that this
# is his formula for success in why he is a destiny in the last writing
# before his death. 3) Hermen Hesse -  *"I can think, I can wait, I can
# fast" 1922*  Herman Hesse's protagonist in Sidartha proclaims, "I can
# think, I can wait, I can fast."
# 
# ** What They Forgot to Tell Us. 
# Doers, the real risk takers, quietly act without ever getting
# recognition. Doers don't write books. Life is execution rather than
# purpose. EXistence itself is of great, great consequence.  
# 

* The Student
:PROPERTIES:
:UNNUMBERED:
:END:

*What we know best* - Knowledge increases as we remove false,
speculative information. Discomfirmation is more rigorous than
confirmation. At a personal level, We know what we disklike more than
what we like. You are much more likely to improve your life by
removing what you dislike rather than what you think you
like. Avoidance of ignorant people is like being around smart ones.

*What's Worth Knowing:* 1) *Time* - Informatino that has been around a long
time will likely be around for a lot longer than the new thing. Prune
"news" sources- TV, radio, social media, etc. Trendy information is
fragile information. Stick to old books 2) *Distribution* -  what a
million people know is not worth knowing. If you know what everyone
else knows, your payoff will be average.  3) *corollary:* in
conjunction with preferring old books, Acquire as many books as you
can possibly own. What you don't know (and no one else knows) is far
more important than what you do. There is no upper limit to what you
don't know. 4) *Learn what can be used immediately.* Information not
put to use is wasted. Knowledge that is personally valuable remains
with you. Learn info that you searched for, never what is curated by
an algorithm. 5) *Learning is repetition* Books are like friends, get
to know them a little at a time. Look through the bibliographies of
your favorite books. The test of whether you really liked a book is to
reread it; the test of whether you really liked someone’s Company is
if you are ready to meet him again and again. Friendship that ends
never was one, any book not worth rereading isn’t worth reading. 

# 24. Reading is for improving the eyes you use to see
#    the world. Don't read best-sellers. Business books are a
#    completely eliminated category by bookstores for writings that
#    have no depth, no style, no empirical rigor and no
#    sophistication. Read history, (not about the last 50 years),
#    philosophy, biography, fiction, the hard sciences, and
#    mathematics. Through learning the basics, it has a place to hook
#    your understanding. It opens up a world of interestingness. 


*How Knowledge Cripples the mind & body* Artificially constructed
environments for the body and mind deprive us of the variablitiy
experienced in real life. This is caled Domain Dependence, and it
cripples us.  Martial arts combat doesn’t train you to a surprise
knife or glock in a street fight. A man checking into a hotel asks the
concierge to take your bags upstairs. Fifteen minutes later, the same
man goes to lift free weights in the hotel gym, replicating with
kettlebells natural exercises as if he were swinging a
suitcase. Skills that transfer: Street fights, off path hiking,
seduction, broad erudition. 

*What our bodies were made for* Random Eposidic stress followed by
ample recovery time. In teh form of  1) Food Restrictions & Volume
Variance The food pyramid has been flipped for the last fifty
years. It is easier to fast than to diet. Eat real foods you enjoy, to
prevent you from eating crap. Eat nothing out of the box. No sugar,
bread, or pasta. Avoid artificial sweeteners. No sweet fruits. Eat
very very large meals on occasion, like Sunday Feasts, while other
times skipping meals. 2) Exercise & Sleep - Do No Moderate Exercise
sessions, either too little or way too much, with no set
schedule. Take Very, very long walks with Occasional sprints. Do No
purely aerobic exercise. Experience variance in body Temperature. Let
yourself become thirsty occasionally. Occasionally sleep deprived, but
default sleep with no alarm clock. In the wild, exercise just
happened. Reward comes after exercise not before, Occasional
abundance. More examples: Childhood immunity is strengthened by
playing in the dirt, Episodic stress to your bones makes them
stronger, Sleeping in absolute silence is difficult. Focus and attention is
sharpened by café chatter or when the speaker whispers. Workout when
you’re hungry. Invers: Avoid sitting all day. An hour in the gym won’t
reverse the effects of 8 hours a day in a chair. Lounge or stand,
never sit. I’d expect a person with a sedentary lifestyle to have at
least one of the following problems: insomnia, depression, anxiety or
lack of focus. Social isolation, nutritional deficiencies, restricted
movement and sleep deprivation are what prisons use to torture its
inmates.

*What Emotions are for:* Emotions are biological signals. They can be
used to aid us in decision making and learning 1) *Procrastination*
Always make decisions at the last minute. Because the longer you wait
the smarter you become. Decisions are best made when the most present
information is available. 2) *Boredom* - Humans don’t like to do
boring things. The purpose of life should be avoiding boredom, or
using boredom as a biological clock,without being impolite If you get
bored easily, your B***t detector is functioning
properly. Beaureaucrats and executives are best at sitting through
boring meetings and keeping attention on boring tasks. Laziness
is enduring an existence you don’t like and never trying to do anything
about it. You don't get a second chance at life if you knowingly
endure boring things. 3) *Forgetfulness*- If you forget (some) things,
it means that our mind knows how to filter 4) *Uncertainty* - The minds
desires certainty while also craving the delicate chance of
surprise. The best days are finding a lost wallet or laptop. You can’t
feel alive and certain at the same time. Having a set schedule and
predictable day makes me feel a little dead. We need to feel a little
bit lost, physically or mentally at least once a day. 5) *Curiosity* —
Read what you like until you like to read. The internet is widening
the gap between the curious and the non curious. Evaluate your
curiosity daily, read accordingly. As soon as a book starts to bore
you, switch. There’s  a perfect book for you waiting to be read. By
keeping score of finished books, you won’t find it. Reading is a
journey to find the best books for you. 6) *urgency &
distractedness* - Deep Learning is never Quickly learned - Trade
speedfor depth-peeding and cramming means you aren’t curious. Trade
speed for depth. If you find yourself doing things that require a
podcast, you should ask yourself whether there’s a better way of doing
it. Rushing is short term thinking. Don’t hurry, don’t stop. An
Internet Sabbath cannot by itself cure a distracted brain.  Instead of
scheduling the occasional break from distraction so you can focus, you
should instead schedule the occasional break from focus to give in to
distraction. 

Within certain limits, never try to convince yourself to do
something. If one reason doesn’t suffice, then don’t do it. Never work
with someone a day that you wouldn’t spend a lifetime with. Never Try
to Convince Yourself. 

The cure for procrastination is changing ones environment or your
profession, where you don’t have to fight your impulses. One should
lead a life in which procrastination is good. “Doing research on a
topic” feels profane. Why would you write about something you can’t
remember? That you wouldn’t use? Let Procrastination kill anything
that I’m putting off too long. Avoid things that don’t give you energy
Embracing nature > fighting nature. 

# Technology can degrade every aspect of a suckers life
#    while convincing him that he is becoming more efficient. The most
#    optimal route is never the shortest one. 
# Cutting corners is
#    dishonest. Automation makes otherwise pleasant activities turn
#    into work.
# *Learning with emotions* 
# 20. 
#    4. You can’t throw hard work and everything and expect anything to
#       be       possible.
# What was taught to me, I forgot, what I learned myself I
# remember.  Too become
#   Learning with Boredom less boring, be bored more. 
#
#    1. Avoid or quit boring activities. 
#    2. Forgetting things is a feature ,not a bug 
#    3. Deciding something is not worth doing anymore 
#    4. People don’t have short attention spans, they just can’t tolerate boredom for too long. 
#    5. You don’t get a 2nd chance. - Boredom. 
# 21. 
# 21. 
#  *Never convince yourself to do anything* 
# future
# *Make mistakes (when small)* errors, never the same error more than
# once. Avoidance of small mistakes makes the large ones more
# severe. Avoidance of hard conversations makes them harder. 
# -  
# Don't listen to what people say, look at what they do. (More on this
# * Learning with Emotions
# - *Avoid Boredom*. Find portals to the classics.  

# * How the body (and other complex systems) learns 
# - *Randomness improves systems* 

*How the mind gets unstuck* intelligent when you don’t instruct it
what to do. Problems will never solved by sitting at a desk. Idle
fascination, letting problems take a back burner that will surface in
the front of your mind when you’re focusing on your problem head
on.Go for a walk without your phone.  A walk is never a waste of
time.  -Walking and sleeping are all mysteriously necessary to have a
healthy life.- Shower, exercise, listening to music.  walk,  swim, or
Dance, Enjoy being a passenger in a car or bus. Ride a bike,  Draw or
paint, Take a bath or shower, Listen to music, especially without
words, Play songs you know well on a musical instrument, Meditate or
pray, or take a nap. By setting oneself totally free of constraints,
free of thoughts, free of this debilitating activity called work, free
of offers, then mysteries that you never thought existed emerge in
front of your eyes. Recognizing a new opportunity requires plenty of
idle time, wandering about, tinkering, trial and error, long walks,
randomized attention. And other inefficiencies of that sort. First
step is recognizing the opportunity. Second step is pouncing on the
good ones. Can’t do any of those things if you squeeze all the idle
time out of life. If you don’t know what your problem is, you need to
sleep. Dreaming is When the conductor falls asleep the orchestra
starts playing on its own accord.

*  The Warrior
:PROPERTIES:
:UNNUMBERED:
:END:

*What Rationality is Good for* 1) *Survival* What is rational is what
allows for  survival.  Uncertainty  doesn’t kill us. Ignoring or not
managing it  does. What is fragile  has more to lose than to gain
Avoid risk of  ruin While dealing with  uncertainty, the worst class
of risk which  you should never tolerate  is those which make you “go
bust,” that  is,which cause irreversible  injury or death, financial
ruin,  betrayal of trust, etc.  In cases  where you are most fragile,
do  whatever it takes to prevent  blows up  from happening. Risk
taking  ain't gambling. 2) *Corollary:* if sometihng appears
irrational, but has existed for a long time, you might need to update
you definition of rational. 

*How Mother Nature Insures Itself* In a word: Redundancy.1)  1. Have
backups.  Redundancy for  both objects and plans are an aggressive
insurance against an unknown future. Avoid planning, Choose the plan
that allows for the most future options. Redundancy is having multiple
ways of doing the same thing.

*What mistakes are for* Address problems while they are small,
ignore good news. Identify  to them when they are small. Hard
conversations get harder the longer you wait to have them. Focus on
picking the low hanging fruit. When someone says they are stupid,
they are more stupid than he thinks. 

*The Practice of Risk Taking* -Some pratical ways: 1) Put your name
on it - Having your  name attached to your idea means you have
something to lose. Honor  and grandeur is standing up for your
opinion at the right  moment. 2) Execution (Deeds
before Words) Think, Learn, and create for an audience. Consistently
post bits and pieces of your work, your ideas, and what you’re
learning online. It’s works, not words, that  make you earn your
title.  2) The line between private and public  life. You must be
consistent with you public ideas and your  private ideas. Never
virtue signal, never The best kind of virtue  gets you put on the
cross. 3) Avoid Cheap Signaling By all means, avoid words. There are
two types of people: those who win and those who try to win
arguments. They are never the  same. Don’t argue, either don’t
complain or eliminate them. 

*Where ideas come from* Creativity is your list of trials. Aggresive
trial and error in domains where randomness rules can help us find 
Options laughing in our faces. Exercise rationality by not
looking in the Same place twice. Presents small errors as
information and large gains which we can exploit when they
arise. If you’re ideas aren’t being rejected outright, you’re not taking
enough risk Being confused is important, or you’re not taking
advantage of the idea space. Confusion is the edge of a
breakthrough. Let it marinate + bother the back of your mind until
the root cause is discovered. A novel root cause implies a new
idea. Come up with 20 ideas. The way to come up with 1 good business
is to create 10 business.s. Trial and error is freedom. You can’t
fail you can only die - which is happening anyway Why should I listen
to you if you put nothing at risk? There is no "failure" for a
risk-taker* 

Provide for the worst case, let the best case take care of itself:
Change a tire in the rain. Whenever I find myself using the phrase
“I have to,” instead  I say “I get to.”  What you own starts owning
you. Consider that Losing all your fortune is much less painful than
only losing half of it. Some people make the mistake of thinking the
worst thing is the worst thing you can think of. It could always be
worse.  When some adverse event takes place, instead of wondering
"why did it happen ?", ask "why wasn't it worse ?.”  When you realize
you are underestimating something, it is likely you are still
underestimating it. What did not happen rather than what did happen. 

*Obvious Red Flags* 1) The most harmful source of Information is advice
advertised (for better or for worse) to help you. There is an
asymmetry between givers of “positiva,” (Do This) prescriptive advice
as they do not incur the harm you would from following their advice.
Avoid commentary from anyone who has to feed their
family. Unsuccessful people give the most advice. 2)Risk Sharing They
still get paid even when you go bust. For best results, just look at
what they do, not what they tell you to do. Another trick is to never
trust the beautiful philosopher.  To filter the credibility of advice,
don’t take advice from the poster child of their profession. If they
don’t play the role or speak the jargon, that means that their skill
speaks for them. 3) Underestimating Luck and Randomness Another factor
that makes advice hard to translate is luck and randomness. Most
communicated advice is flawed: Even if the giver of the advice is
innocuous, advice is like handing you the numbers to their winning
lottery ticket. 

Inverse: Advice to follow The advice you can trust, but is hard to profit from
and thus rarely given, is what to avoid. The ten commandments are all
acts of omission. Trust the advice of old sources (your grandma and old books)

*How to deal with people* Don't Give crap, don't take crap.  Being polite
to someone who is arrogant is worse than being arrogant  to someone
who is polite  Greatness  starts with the replacement of hatred with
polite disdain  Never try to convince yourself to  Don’t be nice or
try to convince,  the FBI didn’t try to convince the mafia.  Verbal
attack is the most  authentic sign of impotence.  You are free in
proportion to the  number of people you can say fuck you to but
don’t. Never trust  someone who doesn’t have any enemies. Stand up
when when others are  afraid for their  reputatio 

# *how to carry yourself* 

*Who "you" are* - Modernity teaches the The collective is more
important than the individual. We are more important than me. Not just
the loss of your life, but one that lies in a broader set of people,
one that includes a family, a community, a tribe, a fraternity. It is
not possible to be ethical and universalist. You are part of a
specific group that is larger than a narrow you but narrower than
humanity in general. Everyone exercises the silver rule. Remember what
others have done for you. And let the instinct of gratitude take over.
If it is good for the community, it is good for me

*What To expect from the future* Randomness always has the last
word. There is little true promise what delayed gratification can do
for us in the real world. Such stresses the impetus to always act
with dignity.  You can choose to call the grapes sour no matter and
free yourself from hope and expectation. Accept what randomness
brings, and act independently of current circumstances. The only
thing fate does not have control over is how you behave. 

* The Philosopher
:PROPERTIES:
:UNNUMBERED:
:END:

*What time is for*  Work should look like play. Weekends shouldn’t
exist. Time changes when you do. Not competing.  Standing out of all
hierarchies. schedules (separate from work as play) no clocks, no wristwatch,
no schedules. Forgetting what day of the week it is.
This makes you a Category of one. Devote yourself to
something. Enjoying your work is the best way to become the best at
what you do. Never try to convince yourself to do something. one
reason doesn’t suffice, then don’t do it. Don’t wobble. Never work
with someone a day that you wouldn’t spend a lifetime with. Never Try
to Convince Yourself. Working hard only recently became prideful
instead of shameful Hard work is a tool. The cure for procrastination
is changing ones environment or your profession, where you don’t have
to fight your impulses. One shouldlead a life in which procrastination
is good. “Doing research on a topic” feels profane. Why would you
write about something you can’t remember?  That you wouldn’t use?  Let
Procrastination kill anything that I’m putting off too long. Avoid
things that don’t give you energy Embracing nature > fighting
nature. Minimize dealing with things you dislike. Some who continually
tells you “I am busy” has no control over their lives or they are
avoiding you. 

# *What to work on* 

*What freedom looks like* The benefit of freedom to
occupy your mind and your  time with only matters that interest
you.To have the freedom to only concern yourself with things you care
about. Work should look like play.  Not competing. Standing out of all
hierarchies. This makes you a Category of one. Devote yourself to
something. Enjoying your work is the best way to become the best at
what you do. Never try to convince yourself to do something. 

*What wealth is* one way to increase your
happiness is to make the place you live in beautiful. Ideally doing
most of it with your own hands. How you react to things. - extreme
ownership. Live with dignity  Do not play victim. Do not
complain. Decouple your self worth from — anything you don’t
control. The only thing you can control is how you react to
things. Everything is my fault. Dress your best. 

*How to live on your own terms*  Don’t do anything that makes you uncomfortable when
you look in the mirror. Better to neither envy nor be envied. You have
a real life if and only if you do not compete with anyone in any of
your pursuits Architects try to impress other artichetects, academics
try to impress other architects, True humility is when you can
surprise yourself more than others. Any action one takes with the aim
of winning an award, any award, corrupts to the core. the greatest
test is how you react when you are insulted in front of a crowd Or
when you get an email from a journalist. Don’t become humble when you
lose everything. We need someone to not impress.  Care about the few
who like it more than the multitude who dislike it. Never say anything
bad about anyone else.  Ignore comments praise and criticism from
people you wouldn’t hire. Don’t signal wealth. Be the person you’d be
when you’re alone.  The squeeze you feel is them putting you into
their box. Their rules, their way, their game. There are no rules, no
boundaries. Play your game; not theirs. Life is not a
competition. There’s no score. Everyone is trying to be the best, or
top %1 percent  Few are trying to do what they like regardless of what
everyone else does.  Competition is for chasing the preferences of
others; playing someone else’s game 




