#+TITLE: Philosophical Notebook 
#+AUTHOR: Joseph Ruocco 

* Introduction 
** Brief Timeline of Related Ideas
** C. 4BC, Roman Empire
It is recorded in response to having suffered a terrible misfortune,
Seneca,(or Zeno of Citium?) the roman statesman is to have reported "Nihil Perditi" - I
have lost nothing. For the Stoics, nothing could have been taken away
from them that they considered a good 
** 1888 Germany 
Nietzche learned from Seneca the Amor Fati - the love of fate. 
He proclaims that this is his formula for success in why he is a
destiny in the last writing before his death. 
** 1922 Hermen Hesse, 
Herman Hesse's protagonist in Sidartha proclaims, "I can think, I can
wait, I can fast." 

* Part I: The Student
** Sources of Knowledge
*** Time Filters Noise
Time judges the judge  What survives and what doesn’t? Fragile  Small
errors, never the same error more than once. Avoidance of small
mistakes makes the large ones more severe. Avoidance of hard
conversations makes them harder. 
*** Subtraction 

** Decision Making under Uncertainty
*** Procrastination
*** Keeping options open
** Learning with Emotions
*** 
** How the body (and other complex systems) learns 
* Part II: The Warrior
** Risk Taking  
*** Rationality as Survival 
Survival comes first. Truth, understanding,and is secondary. There is
no such thing as the rationality of a belief, there is rationality of
action. The rationality of an action can be judged only in terms of
evolutionary considerations. What is rational is that which allows for
survival. Uncertainty doesn’t kill us. Ignoring or not managing it
does. What is fragile has more to lose than to gain Avoid risk of ruin
While dealing with uncertainty, the worst class of risk which you
should never tolerate is those which make you “go bust,” that is,
which cause irreversible injury or death, financial ruin, betrayal of
trust, etc. The foremost easiest way to solve problems is to not have them 
*** 
*** Risk Taking & Failure
** Risk Sharing
** Peer Cruelty 
** 
* Part III: The Philosopher
** Time Management
** Personal Elegance 

** Peer
** Freedom & Self Ownership 


