#+TITLE: Philosophical Notebook 
#+AUTHOR: Joseph Ruocco 

* Introduction 
** Brief Timeline of Related Ideas
*** Nihil Periditi
C. 4BC, Roman Empire - It is recorded in response to having suffered a terrible misfortune,
Seneca,(or Zeno of Citium?) the roman statesman is to have reported "Nihil Perditi" - I
have lost nothing. For the Stoics, nothing could have been taken away
from them that they considered a good 
*** Amor Fati  
1888 Germany - Nietzche learned from Seneca the Amor Fati - the love of fate. 
He proclaims that this is his formula for success in why he is a
destiny in the last writing before his death. 
*** "I can think, I can wait, I can fast"  
1922 Hermen Hesse, - Herman Hesse's protagonist in Sidartha proclaims, "I can think, I can
wait, I can fast." 

* Part I: The Student
** Sources of Knowledge
*** Consider Time
Value what has endured. Only time determines what survives and what
doesn’t. This applies to nearly everything. 

*** Make mistakes (when small)
errors, never the same error more than once. Avoidance of small
mistakes makes the large ones more severe. Avoidance of hard
conversations makes them harder. 

*** Subtract misinformation 
Knowledge is subtractive, that is to say - We know better what is
wrong than what is right. 

*** What you don't know is more important than what you do know. 
Acquire as many books as you can possibly own. 

** Decision Making under Uncertainty
*** Procrastination
Always make decisions at the last minute. Because the longer you wait
the smarter you become. Decisions should be made when the most present
information is available. 

*** Keeping options open
Choose the plan that allows for the most future options. 

*** Never convince yourself to do anything. 


** Learning with Emotions
*** Use Boredom as a compass.  
*** 

** How the body (and other complex systems) learns 
*** Randomness improves systems 


* Part II: The Warrior
** Risk Taking  
*** Take risks, but always be prudent. 
What is rational is that which allows for
survival. Uncertainty doesn’t kill us. Ignoring or not managing it
does. What is fragile has more to lose than to gain Avoid risk of ruin
While dealing with uncertainty, the worst class of risk which you
should never tolerate is those which make you “go bust,” that is,
which cause irreversible injury or death, financial ruin, betrayal of
trust, etc. The foremost easiest way to solve problems is to not have
them 
Risk taking ain't gambling.
*** 
*** There is no "failure" for a risk-taker
** Risk Sharing
** Peer Cruelty 
** 
* Part III: The Philosopher
** Time Management
*** Eschew busyness, avoid entrapment 
*** 
** Personal Elegance 
*** 

** Peer
*** True equality 
** Freedom & Self Ownership 
*** Avoid entrapment. 

