#+TITLE: Philosophical Notebook 
#+SUBTITLE: or, What Our Ancestors Forgot to Tell Us 
#+OPTIONS: toc:nil 
#+AUTHOR: Joseph Ruocco 

* Introduction 
** Old wisdom stays young
The importance of Ancient ideas are because they are so old. Old ideas
have stood the test of time. 

There is an allure that ancient philosophy speaks to the right
soul. The art of Living well the real "moral" philopshers taught was
to approcah life with humility and love of our Nature, its beauty,
knowledge, and uncertainty. 
The Stoics, the skeptics, the epicureans, other ancient schools of
thought. They were all right. We humans, curious by nature, need to
explore, adventure, rationally stepping forward by keeping what suits
us and discarding the rest. Ethics are different at scale. IN random
domains. With risk taking I'm a stoic, with knowledge I'm a
skepticist/empiricst, with aesthetics I'm an epicurean.    
If we seek to fill the shoes of our ancestors,to have the same impact
as our ancestors.  We have to devote ourselves to risk taking. We have
to prudently prepare for a world we don't quite know what to expect
from. We have to take up what our ancestors left behind.  Of course,
like Seneca, we can keep the fruits and enjoy life.  

** Several Proclamations around a central Stoic Idea. . 
Few figures stress the importnace of robustness than the Stoics. And
the heavy criticality of this idea its not surprising that fellows
separated by continents or centuries have the same idea: 1) *Nihil
Periditi, C. 4BC, Roman Empire* - It is recorded in response to having
suffered a terrible misfortune, Seneca,(or Zeno of Citium?) the roman
statesman is to have reported "Nihil Perditi" - I have lost
nothing. For the Stoics, nothing could have been taken away from them
that they considered a good. Nearly all the letters of Seneca echo
against loss aversion. 2) *Amor Fati 1888 Germany* Nietzche learned
from Seneca the Amor   Fati - the love of fate. He proclaims that this
is his formula for success in why he is a destiny in the last writing
before his death. 3) Hermen Hesse -  *"I can think, I can wait, I can
fast" 1922*  Herman Hesse's protagonist in Sidartha proclaims, "I can
think, I can wait, I can fast."

** What They Forgot to Tell Us. 
Doers, the real risk takers, quietly act without ever getting
recognition. Doers don't write books. Life is execution rather than
purpose. EXistence itself is of great, great consequence.  

* The Student

*Evaluating & Curating Sources of INformation* - 1) Knowledge
increases as we remove false, speculative information. We know what we
disklike more than what we like. You are much more likely to improve
your life by removing what you dislike rather than what you think you
like. Avoidance of ignorant people is like being around smart ones. 2)
Judging information: First, time filters noise. Informatino that has
been around a long time will likely be around for a lot longer than
the new thing. Prune "news" sources- TV, radio, social media,
etc. Stick to old books. Second, in conjunction with preferring old
books,Acquire as many books as you can possibly own.  What you don't
know is far more important than what you do. There is no upper limit
to what you don't know. 




        1. Laziness is enduring an existence you don’t like and never
           trying to do anything about it. If you like your life, and
           Theres nothing to change. You don’t have to Impact >
           replaceable. 

    4. You can’t throw hard work and everything and expect anything to
       be       possible.



*Decision making under uncertainty* 1) Procrastination* Always make
decisions at the last minute. Because the longer you wait the smarter
you become. Decisions should be made when the most present information
is available. 2)  *Keeping options open* Choose the plan that allows
for the most

*Domain Dependence* Martial arts combat doesn’t train you to a
surprise knife or glock in a street fight. Resist people
movers. Embrace stairs, avoid elevators. Don’t take the car to get on
the treadmill. Treadmills are cheap on craigslist. Buy or make  your
own desk. A man checking into a hotel asks the concierge to take your
bags upstairs. Fifteen minutes later, the same man goes to lift free
weights in the hotel gym, replicating with kettlebells natural
exercises as if he were swinging a suitcase. Skills that transfer:
Street fights, off path hiking, seduction, broad erudition, 


*Learning with emotions* 
20. Boredom and Forgetfulness. Avoid Boredom, Follow Curiosity. IN
    learning and life, getting bored easily is functioning properly.
    Humans don’t like to do boring things. The    purpose of life
    should be avoiding boredom, or using boredom as a    biological
    clock,without being impolite If you get bored easily

If you forget (some) things, it means that your mind knows how to
 filter 
 What was taught to me, I forgot, what I learned myself I
 remember. Beaureaucrats and executives are best at sitting through
 boring meetings and keeping attention on boring tasks. Too become

   Learning with Boredom less boring, be bored more. 

    1. Avoid or quit boring activities. 
    2. Forgetting things is a feature ,not a bug 
    3. Deciding something is not worth doing anymore 
    4. People don’t have short attention spans, they just can’t tolerate boredom for too long. 
    5. You don’t get a 2nd chance. - Boredom. 

21. Learn subjects through curiosity — Read what you like until you
    like to read. The internet is widening the gap between the curious
    and the non curious. Evaluate your curiosity daily, read
    accordingly.Curiosity should lead to deep, specific knowledge. Let
    that be a barometer for learning, not the strange
    reading-as-an-obligation. With a fine-tuned curiosity, you will
    start with a narrow topic and then ultimately be able to read
    anything. Follow anything that stimulates deep
    curiosity. Curiosity is infinite.  As soon as a book starts to
    bore you, switch. And you find gold, so to speak, effortlessly,
    just as in rational but undirected trial-and-error-based
    research. To “only eat what you kill” in the Information Age is
    only learning information that you searched for.  (See 15) There’s
    a perfect book for you waiting to be read. By keeping score of
    finished books, you won’t find it. Reading is a journey to find
    the best books for you. find an interesting side door to a topic
    you’ve never heard about. 


21. Deep Learning is never Quickly learned. Trade speed for depth
    Speeding and cramming means you aren’t    curious. Trade speed for depth. If you find yourself doing things
    that require a podcast, you should ask yourself whether there’s a
    better way of doing it. Rushing is short term thinking. Don’t
    hurry, don’t stop. Optimization. Cutting corners is
    dishonest. Automation makes otherwise pleasant activities turn
    into work. Technology can degrade every aspect of a suckers life
    while convincing him that he is becoming more efficient. The most
    optimal route is never the shortest one. Some who continually
    tells you “I am busy” has no control over their lives or they are
    avoiding you. 

Books and Friends - Books are like friends, get to know them a little
at a time. Look through the bibliographies of your favorite books. Go
down the rabbit hole. The test of whether you really liked a book is
to reread it; the test of whether you really liked someone’s. Company
is if you are ready to meet him again and again. Friendship that ends
never was one, any book not worth rereading isn’t worth
reading. Choose the few that are most important, and spend a lifetime
reading and rereading them. Get to know them a little at a time


*Avoiding Fossilization* 


  *Never convince yourself to do anything* 
future



 *Make mistakes (when small)* errors, never the same error more than
 once. Avoidance of small mistakes makes the large ones more
 severe. Avoidance of hard conversations makes them harder. 


- 
Don't listen to what people say, look at what they do. (More on this




** Learning with Emotions
- *Avoid Boredom*. Find portals to the classics.  

** How the body (and other complex systems) learns 
- *Randomness improves systems* 


* The Warrior
 *Take risks, but always be prudent.* What is rational is that which
  allows for survival. Uncertainty doesn’t kill us. Ignoring or not
  managing it does. What is fragile has more to lose than to gain
  Avoid risk of ruin While dealing with uncertainty, the worst class
  of risk which you should never tolerate is those which make you “go
  bust,” that is,which cause irreversible injury or death, financial
  ruin, betrayal of trust, etc. The foremost easiest way to solve
  problems is to not have them. Risk taking ain't gambling.
    1. Put your name on it - Having your name attached to your idea means you have something to lose. Honor and grandeur is standing up for your opinion at the right moment. Virtue is a sequence of small acts of omission. 
    2. Work in front of others.  (Deeds before Words) Think, Learn,
       and create for an audience. Consistently post bits and pieces
       of your work, your ideas, and what you’re learning online.
       It’s works, not words, that make you earn your title. 
 The line between private and public life. You must be consistent with
 you public ideas and your 	private ideas. Never virtue signal,
 never The best kind of virtue gets you put on the cross. Be who you
 are when alone.

    3. Non Cheap Signaling By all means, avoid words. There are two
       types of people: those who win and those who try to win
       arguments. They are never the same. Don’t argue, either don’t
       complain or eliminate them. From a distance you can’t tell what
       their arguing about, up close they can’t tell what they’re
       arguing about either. Being polite to someone who is arrogant
       is worse than being arrogant to someone who is polite Greatness
       starts with the replacement of hatred with polite disdain
       Never try to convince yourself to  Don’t be nice or try to
       convince, the FBI didn’t try to convince the mafia.  Verbal
       attack is the most authentic sign of impotence.  You are free
       in proportion to the number of people you can say fuck you to
       but don’t. Never trust someone who doesn’t have any
       enemies. Stand up when when others are afraid for their
       reputation 

    4. Why should I listen to you if you put nothing at risk? 

Redundancy. 
- *There is no "failure" for a risk-taker* 
    1. Have backups. Not just for physical objects but for plans. Redundancy for both objects and plans are an aggressive insurance against an unknown future. The benefit of freedom to occupy your mind and your time with only matters that interest you. 

    2. Choose plans with the most amount of options. Such a life as this finds ourself with a lot of Downtime. Keep a notebook with you at all times. Carrying a book with you at all times me access to a large selection of books to learn on-the-go. (which makes the necessarily painful moments of waiting in line) Have no loyalty to location, corporation, or your past public statements. Be an absolute opportunist doing whatever is best for the future in the current situation, unbound by the past. Have loyalty for only your most important human relationships. Living requires optionality. You need the freedom to explore and some aimless wandering. 
    3. Make decisions as late as possible. Don’t make appointments except for the same day. Also, tell friends you’re coming an hour later than you plan on arriving.  

    4. Option blindness - when we obsess on trying to achieve X we become blind to better options that are not conducive to X. 
    5. Redundancy is having multiple ways of doing the same thing. 

37. Work should look like play. Weekends shouldn’t exist. Time changes
    when you do. Not competing.  Standing out of all hierarchies. This
    makes you a Category of one. Devote yourself to
    something. Enjoying your work is the best way to become the best
    at what you do. Never try to convince yourself to do something. If
    one reason doesn’t suffice, then don’t do it. Don’t wobble. Never
    work with someone a day that you wouldn’t spend a lifetime
    with. Never Try to Convince Yourself.  Working hard only recently
    became prideful instead of shameful Hard work is a tool. The cure
    for procrastination is changing ones environment or your
    profession, where you don’t have to fight your impulses. One
    should lead a life in which procrastination is good. “Doing
    research on a topic” feels profane. Why would you write about
    something you can’t remember?  That you wouldn’t use?  Let
    Procrastination kill anything that I’m putting off too long. Avoid
    things that don’t give you energy Embracing nature > fighting
    nature. Minimize dealing with things you dislike 



32. Address problems while they are small, ignore good news. Identify
    to them when they are small. Hard conversations get harder the
    longer you wait to have them. Focus on picking the low hanging
    fruit. When someone says they are stupid, they are more stupid
    than he thinks. 

31. Provide for the worst case, let the best case take care of itself:
    Change a tire in the rain. Whenever I find myself using the phrase
    “I have to,” instead  I say “I get to.”  What you own starts
    owning you. Consider that Losing all your fortune is much less
    painful than only losing half of it. Some people make the mistake
    of thinking the worst thing is the worst thing you can think
    of. It could always be worse.  When some adverse event takes
    place, instead of wondering "why did it happen ?", ask "why wasn't
    it worse ?.”  When you realize you are underestimating something,
    it is likely you are still underestimating it. What did not happen
    rather than what did happen 


** Risk Sharing
    1.  Obvious Red FlagsThe most harmful source of Information is
       advice advertised (for better or for worse) to help you. There
       is an asymmetry between givers of “positiva,” (Do This)
       prescriptive advice as they do not incur the harm you would
       from following their advice.  Avoid commentary from anyone who
       has to feed their family. Unsuccessful people give the most
       advice. 

    2. Risk Sharing They still get paid even when you go bust. For
       best results, just look at what they do, not what they tell you
       to do. Another trick is to never trust the beautiful
       philosopher.  To filter the credibility of advice, don’t take
       advice from the poster child of their profession. If they don’t
       play the role or speak the jargon, that means that their skill
       speaks for them. 

    3. Luck and Randomness Another factor that makes advice hard to
       translate is luck and randomness. Most communicated advice is
       flawed: Even if the giver of the advice is innocuous, advice is
       like handing you the numbers to their winning lottery ticket. 

    4. Advice to follow The advice you can trust, but is hard to
       profit from and thus rarely given, is what to avoid. The ten
       commandments are all acts of omission. Trust the advice of old
       sources (your grandma and old books)

** Peer Cruelty 

 We over Me    - The collective is more important than the
 individual. We are more important than me. Not just the loss of your
 life, but one that lies in a broader set of people, one that includes
 a family, a community, a tribe, a fraternity. It is not possible to
 be ethical and universalist. You are part of a specific group that is
 larger than a narrow you but narrower than humanity in
 general. Everyone exercises the silver rule. Remember what others
 have done for you. And let the instinct of gratitude take over. Don’t
 give crap don’t take crap. If it is good for the community, it is
 good for me






* The Philosopher
** Time Management
- *Eschew busyness, avoid entrapment*
37. Work should look like play. Weekends shouldn’t exist. Time changes
    when you do. Not competing.  Standing out of all hierarchies. This
    makes you a Category of one. Devote yourself to
    something. Enjoying your work is the best way to become the best
    at what you do. Never try to convince yourself to do something. If
    one reason doesn’t suffice, then don’t do it. Don’t wobble. Never
    work with someone a day that you wouldn’t spend a lifetime
    with. Never Try to Convince Yourself.  Working hard only recently
    became prideful instead of shameful Hard work is a tool. The cure
    for procrastination is changing ones environment or your
    profession, where you don’t have to fight your impulses. One
    should lead a life in which procrastination is good. “Doing
    research on a topic” feels profane. Why would you write about
    something you can’t remember?  That you wouldn’t use?  Let
    Procrastination kill anything that I’m putting off too long. Avoid
    things that don’t give you energy Embracing nature > fighting
    nature. Minimize dealing with things you dislike 
x

** Personal Elegance
40. Aesthetics and personal elegance. - one way to increase your
    happiness is to make the place you live in beautiful. Ideally
    doing most of it with your own hands. How you react to things. -
    extreme ownership. Live with dignity  Do not play victim. Do not
    complain. Decouple your self worth from — anything you don’t
    control. The only thing you can control is how you react to
    things. Everything is my fault. Dress your best. 
44.  schedules (separate from work as play) no clocks, no wristwatch,
    no schedules. Forgetting what day of the week it is.


** Peer
- *True equality* 

36. Peer Envy - Don’t do anything that makes you uncomfortable when
    you look in the mirror. Better to neither envy nor be envied. You
    have a real life if and only if you do not compete with anyone in
    any of your pursuits Architects try to impress other artichetects,
    academics try to impress other architects, True humility is when
    you can surprise yourself more than others. Any action one takes
    with the aim of winning an award, any award, corrupts to the
    core. the greatest test is how you react when you are insulted in
    front of a crowd Or when you get an email from a journalist. Don’t
    become humble when you lose everything. We need someone to not
    impress.  Care about the few who like it more than the multitude
    who dislike it. Never say anything bad about anyone else.  Ignore
    comments praise and criticism from people you wouldn’t hire. Don’t
    signal wealth. Be the person you’d be when you’re alone 

    1. The squeeze you feel is them putting you into their box. Their
       rules, their way, their game. There are no rules, no
       boundaries. Play your game; not theirs. 


    2. Life is an adventure, not a competition. A good life isa
       stoorre you’re proud of. There’s no score. Everyone is trying
       to be the best, or top %1 percent  Few are trying to do what
       they like regardless of what everyone else does.  Competition
       is for chasing the preferences of others; playing someone
       else’s game 

** Freedom & Self Ownership 

- *Avoid entrapment* 

